<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE webpage [
<!ELEMENT academicyear ( #PCDATA ) >

<!ELEMENT address ( #PCDATA ) >

<!ELEMENT article ( author | journal | note | number | pages | pdf-available | pdfslides-available | ps-available | title | volume | year )* >
<!ATTLIST article key ID #REQUIRED >

<!ELEMENT author ( #PCDATA ) >

<!ELEMENT booktitle ( #PCDATA ) >

<!ELEMENT contactinfo ( name, picture, phone, fax, emailaddress, postaladdress ) >

<!ELEMENT dayofweek ( #PCDATA ) >

<!ELEMENT degree ( #PCDATA ) >

<!ELEMENT editor ( #PCDATA ) >

<!ELEMENT editors ( #PCDATA ) >

<!ELEMENT emailaddress ( #PCDATA ) >

<!ELEMENT englishdegree ( #PCDATA ) >

<!ELEMENT englishname ( #PCDATA ) >

<!ELEMENT extra-links ( link+ ) >

<!ELEMENT fax ( #PCDATA ) >

<!ELEMENT hour ( #PCDATA ) >

<!ELEMENT inbook ( address | author | booktitle | editors | note | pages | pdf-available | ps-available | publisher | series | title | volume | year )* >

<!ATTLIST inbook key NMTOKEN #REQUIRED >

<!ELEMENT inproceedings ( address | author | booktitle | editor | editors | note | pages | pdf-available | pdfslides-available | ps-available | publisher | series | title | volume | year )* >

<!ATTLIST inproceedings key ID #REQUIRED >

<!ELEMENT misc (  author | title | note | pdf-available | pdfslides-available | ps-available | year | howpublished )* >

<!ATTLIST misc key ID #REQUIRED >

<!ELEMENT journal ( #PCDATA ) >

<!ELEMENT line ( #PCDATA ) >
<!ATTLIST line url CDATA #IMPLIED >

<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link lang ( ca | en ) #REQUIRED >
<!ATTLIST link url CDATA #REQUIRED >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT note ( #PCDATA | noteurl )* >

<!ELEMENT noteurl ( #PCDATA ) >

<!ELEMENT number ( #PCDATA ) >

<!ELEMENT officehours ( validity, segment* ) >

<!ELEMENT pages ( #PCDATA ) >

<!ELEMENT pdf-available EMPTY >

<!ELEMENT pdfslides-available EMPTY >

<!ELEMENT phone ( #PCDATA ) >

<!ELEMENT picture ( #PCDATA ) >

<!ELEMENT postaladdress ( line+ ) >

<!ELEMENT ps-available EMPTY >

<!ELEMENT publications ( article | inbook | inproceedings | misc )* >

<!ELEMENT publisher ( #PCDATA ) >

<!ELEMENT segment ( dayofweek, hour ) >

<!ELEMENT series ( #PCDATA ) >

<!ELEMENT subject ( name, englishname, degree, englishdegree, url? ) >

<!ELEMENT teaching ( academicyear, subject+ ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT url ( #PCDATA ) >

<!ELEMENT validity ( #PCDATA ) >

<!ELEMENT volume ( #PCDATA ) >

<!ELEMENT webpage ( publications, contactinfo, officehours, teaching, extra-links ) >

<!ELEMENT year ( #PCDATA ) >


]>
<webpage>
  <publications>
	  
	  <inproceedings key="scarton19p">
      <author>Scarton, C., Forcada, M.L., Esplà-Gomis, M., Specia, L.</author>
      <title>Estimating post-editing effort: a study on human judgements, task-based and
reference-based metrics of MT quality</title>
      <year>2019</year>
      <booktitle>Proceedings of IWSLT 2019</booktitle>
      <note>Hong Kong, Nov. 2-3, 2019</note>
      <pdf-available/>
</inproceedings>

    <article key="espla18j">
      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>Predicting insertion positions in word-level machine translation quality estimation</title>
      <journal>Applied Soft Computing</journal>
      <year>2019</year>
      <volume>79</volume>
      <pages>174-192</pages>
      <note>https://doi.org/10.1016/j.asoc.2018.11.036</note>
      <pdf-available/>
    </article>
    
    
    
    
    <inproceedings key="forcada18p">
      <author>Forcada, M.L., Scarton, C., Specia, L., Haddow, B., Birch, A.</author>
      <title>Exploring Gap Filling as a Cheaper Alternative to Reading Comprehension Questionnaires when Evaluating Machine Translation for Gisting</title>
      <pages>192-203</pages>
      <year>2018</year>
      <booktitle>Proceedings of the 3rd Conference on Machine Translation (WMT18)</booktitle>
      <note>Brussels, Oct. 31-Nov. 1, 2018</note>
      <pdf-available/>
</inproceedings>

    <inproceedings key="forcada18p2">
      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>UAlacant machine translation quality estimation at WMT 2018: a simple approach using phrase tables and feed-forward neural networks</title>
      <pages>814-823</pages> -->
      <year>2018</year>
      <booktitle>Proceedings of the 3rd Conference on Machine Translation (WMT18)</booktitle>
      <note>Brussels, Oct. 31-Nov. 1, 2018</note>
      <pdf-available/>
</inproceedings>

    <inproceedings key="koehn18p">
      <author>Koehn, P.,  Khayrallah, H., Heafield, K., Forcada, M.L.</author>
      <title>Findings of the WMT 2018 Shared Task on Parallel Corpus Filtering</title>
      <pages>739-752</pages> 
      <year>2018</year>
      <booktitle>Proceedings of the 3rd Conference on Machine Translation (WMT18)</booktitle>
      <note>Brussels, Oct. 31-Nov. 1, 2018</note>
      <pdf-available/>
</inproceedings>

    <article key="forcada17j2">
      <author>Forcada, M.L.</author>
      <title>Making sense of neural machine translation</title>
      <journal>Translation Spaces</journal>
      <year>2017</year>
      <volume>6</volume>
      <number>2</number>
      <pages>291-309</pages>
      <note>Author's preprint. Published paper under copyright. Contact John Benjamins Publishing Company if you need permission to reuse or reprint the material in any form.</note>
      <pdf-available/>
    </article>
	

<inproceedings key="forcada17p">
<author>Forcada, M.L., Esplà-Gomis, M., Sánchez-Martínez, F., Specia, L.</author>
<title>One-parameter models for sentence-level post-editing effort estimation</title>
<pages>132-143</pages>
<year>2017</year>
<booktitle>Proceedings of MT Summit XVI, vol.1: Research Track</booktitle>
<note>Nagoya, Sep. 18-22, 2017</note>
<pdf-available/>
</inproceedings>




<inproceedings key="jordan17p">
<author>Jordan-Núñez, K., Forcada, M.L., Clua, E.</author>
<title>Usefulness of MT output for comprehension -
 an analysis from the point of view of
linguistic intercomprehension</title>
<pages>241-253</pages>
<year>2017</year>
<booktitle>Proceedings of MT Summit XVI, vol.1: Research Track</booktitle>
<note>Nagoya, Sep. 18-22, 2017</note>
<pdf-available/>
</inproceedings>

    <inproceedings key="ortega16p">
      <author>Ortega, J.E., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>Fuzzy-match repair using black-box machine translation systems: what can be expected?</title>
      <booktitle>Proceedings of AMTA 2016, vol. 1: MT Researchers' track</booktitle>
      <pages>27-39</pages>
      <note>Austin, Oct. 28 - Nov. 1, 2016.</note>
      <year>2016</year>
      <pdf-available/>
    </inproceedings>

<misc key="bel16p">
	<author>Bel, N., Forcada, M.L., Gómez-Pérez, A.</author>
	<title>A Maturity Model for Public Administration Open Translation Data	Providers</title>
	<howpublished>https://arxiv.org/pdf/1607.01990.pdf</howpublished>
	<year>2016</year>
	<note>Presented at MetaForm 2016, Lisbon, July 4-5.</note>
	<pdf-available/>
	<pdfslides-available/>
</misc>


    <inproceedings key="torregrosa16p">
      <author>Torregrosa, D., Pérez-Ortiz, J.A., Forcada, M.L.</author>
      <title>Ranking suggestions for black-box interactive
translation prediction systems with multilayer
perceptrons</title>
      <booktitle>Proceedings of AMTA 2016, vol. 1: MT Researchers' track</booktitle>
      <pages>65-78</pages>
      <note>Austin, Oct. 28 - Nov. 1, 2016.</note>
      <year>2016</year>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="torregrosa16p2">
      <author>Torregrosa, D., Pérez-Ortiz, J.A., Forcada, M.L.</author>
      <title>Comparison of two different interactive translation
prediction approaches integrated in a
computer-assisted translation workbench</title>
      <booktitle>AMTA 2016 Workshop on Interacting with Machine Translation (iMT 2016)</booktitle>
      <pages>-</pages>
      <note>Austin, Oct. 28, 2016.</note>
      <year>2016</year>
      <pdf-available/>
    </inproceedings>
  
    <inproceedings key="espla16p2">
      <author>Esplà-Gomis, M., Forcada, M.L., Ortiz-Rojas, S., Ferrández-Tordera, J.</author>
      <title>Bitextor's participation in WMT'16: shared task on document alignment</title>
      <booktitle>ACL 2016: First Conference on Machine Translation (WMT16)</booktitle>
      <pages>685-691</pages>
      <note>Berlin, Germany, August 11 and 12, 2016</note>
      <year>2016</year>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="espla16p3">
      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>UAlacant word-level and phrase-level machine translation quality estimation systems at WMT 2016</title>
      <booktitle>ACL 2016: First Conference on Machine Translation (WMT16)</booktitle>
      <pages>728-786</pages>
      <note>Berlin, Germany, August 11 and 12, 2016</note>
      <year>2016</year>
      <pdf-available/>
    </inproceedings>

    <article key="forcada17j">
      <author>Forcada, M.L., Sánchez-Martínez, F., Esplà-Gomis, M., Specia, L.</author>
      <title>Towards Optimizing MT for Post-Editing Effort: Can BLEU Still Be Useful?</title>
      <journal>Prague Bulletin of Mathematical Linguistics</journal>
      <year>2017</year>
      <volume>108</volume>
      <pages>183-195</pages>
      <pdf-available/>
    </article>
      
    <article key="torregrosa17j">
      <author>Torregrosa, D., Pérez-Ortiz, J.A., Forcada, M.L.</author>
      <title>Comparative Human and Automatic Evaluation of Glass-Box
and Black-Box Approaches to Interactive Translation Prediction</title>
      <journal>Prague Bulletin of Mathematical Linguistics</journal>
      <year>2017</year>
      <volume>108</volume>
      <pages>97-108</pages>
      <pdf-available/>
    </article>


    

    <article key="espla16j">
      <author>Esplà-Gomis, M., Carrasco, R.C., Sánchez-Cartagena, V.M., Forcada, M.L., Sánchez-Martínez, F., Pérez-Ortiz, J.A.</author>
      <title>Assisting non-expert speakers of under-resourced languages in assigning stems and inflectional paradigms to new word entries of morphological dictionaries</title>
      <journal>Language Resources and Evaluation</journal>
      <year>2016</year>
      <volume>50</volume>
      <pages></pages>
      <note>https://doi.org/10.1007/s10579-016-9360-9</note>
      <pdf-available/>
    </article>

    <article key="forcada16j">
      <author>Forcada, M.L., Esplà-Gomis, M., Pérez-Ortiz, J.A.</author>
      <title>Stand-off Annotation of Web Content as a Legally
Safer Alternative to Crawling for Distribution</title>
      <journal>Baltic Journal of Modern Computing</journal>
      <year>2016</year>
      <volume>4</volume>
      <number>2</number>
      <pages>152-164</pages>
      <note>(proceedings of the 19th Annual Conference of the European Association for Machine Translation, Riga, Latvia, May 30 - June 1, 2016)</note>
      <pdf-available/> 
    </article>

  
    <misc key="chen15m">
      <author>Chen, G., Forcada M.L.</author>
      <title>A Light Sliding-Window Part-of-Speech Tagger for the Apertium Free/Open-Source Machine Translation Platform</title>
      <howpublished>http://arxiv.org/abs/1509.05517</howpublished>
      <year>2015</year>
      <pdf-available/>
    </misc>

    <misc key="espla12m">
      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>Using external sources of bilingual information for on-the-fly
word alignment</title>
      <howpublished>http://arxiv.org/abs/1212.1192</howpublished>
      <year>2012</year>
      <pdf-available/>
    </misc>


    <inproceedings key="espla15p2">

      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>UAlacant word-level machine translation quality estimation system at
WMT 2015</title>
      <booktitle>EMNLP 2015. Tenth Workshop on Statistical Machine Translation. Proceedings of the Workshop </booktitle>
      <pages>309-315</pages>
      <note>Lisbon, Portugal, September 17 and 18, 2015</note>
      <year>2015</year>
      <pdf-available/>
    </inproceedings>



    <article key="toral15p">
      <journal>Procesamiento del Lenguaje Natural</journal>
      <volume>55</volume>
      <year>2015</year>
      <pages>185-188</pages>
      <author>Toral, A., Pirinen, T., Way, A., Rubino, R., Ramírez-Sánchez, G.,  Ortiz-Rojas, S., Sánchez-Cartagena, V.M., Ferrández-Tordera, J., Forcada, M.L., Esplà-Gomis, M., Ljubesic, N., Klubicka, F., Prokopidis, P., Papavassiliou, V. </author>
      <title>Automatic Acquisition of Machine Translation Resources in the
Abu-MaTran Project</title>
      <pdf-available/>
    </article>

    <article key="espla15j">
      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>Using Machine Translation to Provide Target-Language Edit Hints in Computer Aided Translation Based on Translation Memories</title>
      <journal>Journal of Artificial Intelligence Research</journal>
      <year>2015</year>
      <volume>53</volume>
      <pages>169-222</pages>
      <pdf-available/>
    </article>


    <inproceedings key="espla15p">
      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>Using on-line available sources of bilingual information for word-level machine translation quality estimation</title>
      <year>2015</year>
      <booktitle>Proceedings of 2015, The Eigtheenth Annual Conference of the European Association for Machine Translation</booktitle>
     <pages>19-26</pages> 
      <note>Antalya, May 11-13, 2015</note>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="forcada15p">
      <author>Forcada, M.L., Sánchez-Martínez, F.</author>
      <title>A general framework for minimizing translation effort:
towards a principled combination of translation technologies in
computer-aided translation</title>
      <year>2015</year>
      <booktitle>Proceedings of EAMT 2015, The Eigtheenth Annual Conference of the European Association for Machine Translation</booktitle>
     <pages>27-34</pages> 
      <note>Antalya, May 11-13, 2015</note>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="ageeva15p">
      <author>Ageeva, E., Forcada, M.L., Tyers, F.M., Pérez-Ortiz, J.A. </author>
      <title>Evaluating machine translation for assimilation via a gap-filling task</title>
      <year>2015</year>
      <booktitle>Proceedings of EAMT 2015, The Eigtheenth Annual Conference of the European Association for Machine Translation</booktitle>
     <pages>137-144</pages> 
      <note>Antalya, May 11-13, 2015</note>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="tyers15p">
      <author>Tyers, F.M., Sánchez-Martínez, F., Forcada, M.L. </author>
      <title>Unsupervised training of maximum-entropy models for lexical selection in
rule-based machine translation</title>
      <year>2015</year>
      <booktitle>Proceedings of EAMT 2015, The Eigtheenth Annual Conference of the European Association for Machine Translation</booktitle>
     <pages>145-152</pages> 
      <note>Antalya, May 11-13, 2015</note>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="ortega14p">
      <author>Ortega, J.E., Forcada, M.L., Sánchez-Martínez, F.</author>
      <title>Using any machine translation source for
fuzzy-match repair in a computer-aided translation
setting</title>
      <booktitle>Proceedings of the
11th Conference of the Association for 
Machine Translation in the Americas,
Vol. 1: MT Researchers Track</booktitle>
      <year>2014</year>
      <editors>Yaser al Onaizan, Michel Simard</editors>
      <note>Vancouver, BC, Canada, Oct. 22-26, 2014</note>
     <pages>42-53</pages>
      <pdf-available/>
    </inproceedings>


    <article key="torregrosa14j">
      <author>Daniel Torregrosa, Mikel L. Forcada, Juan Antonio Pérez-Ortiz</author>
      <title>An open-source web-based tool
for resource-agnostic interactive translation prediction</title>
      <journal>The Prague Bulletin of Mathematical Linguistics</journal>
      <volume>102</volume>
      <year>2014</year>
      <pages>69-80</pages>
      <pdf-available/>
    </article>

<article key="forcada13p">
<title>
Peeking through the language barrier: the development of a free/open-source gisting system for Basque to English based on apertium.org
</title>
<author>J. O'Regan, M.L. Forcada</author>
<journal>Procesamiento del Lenguaje Natural</journal>
<note>XXIX Congreso de la Sociedad Española de Procesamiento del
Lenguaje Natural, Madrid, Spain, 16-18.09.2013</note>
<volume>51</volume>
<pages>15-22</pages>
<year>2013</year>
<pdf-available/>
<pdfslides-available/>
</article>


<inbook key="forcada12lfm">
<author>Mikel L. Forcada
</author>
<title>Traducció automàtica de codi obert: Apertium, una oportunitat per a les
llengües menors</title>
<booktitle>Les fronteres del multilingüisme: una visió actual i pluridisciplinar sobre el multilingüisme en la societat contemporània</booktitle>
<publisher>Editorial UOC</publisher>
<editors>Bos i Solé, A.</editors>
<pages>57-80</pages>
<year>2012</year>
</inbook>



    <article key="espla12j">
      <author>Esplà-Gomis, M., Sánchez-Martínez, F., Forcada, M.L.</author>
      <title>A Simple Approach to Use Bilingual Information Sources for Word Alignment</title>
      <journal>Procesamiento del Lenguaje Natural</journal>
      <volume>49</volume>
      <pages>93-100</pages>
      <year>2012</year>
      <pdf-available/>
    </article>

    <inbook key="forcada10mtt">
      <title>Machine Translation Today</title>
      <author>Mikel L. Forcada</author>
      <booktitle>Handbook of Translation Studies</booktitle>
      <volume>1</volume>
      <pages>215-223</pages>
      <year>2010</year>
      <editors>Yves Gambier, Luc Van Doorslaer</editors>
    </inbook>

    <inbook key="forcada11fgc">
      <title>Traducció automàtica</title>
      <author>Mikel L. Forcada</author>
      <booktitle>La lingüística i les seues aplicacions en la societat</booktitle>
      <pages>115-132</pages>
      <year>2011</year>
      <editors>Colón Doménech, G., Gimeno Betí, L.</editors>
    </inbook>


    <inproceedings key="sundetova13p">
      <author>Sundetova, A., Forcada, M.L., Shormakova, A., Aitkulova, A.</author>
      <title>Structural transfer rules for English-Kazakh machine translation inthe free/open-source platform Apertium</title>
      <year>2013</year>
      <booktitle>Proceedings of the I International Conference on Computer Procfessing of Turkic Languages (TurkLang-2013)</booktitle>
<!--      <pages></pages> -->
      <pages>322-331</pages>
      <note>Astana, 3-4 oct. 2013</note>
      <pdf-available/>
    </inproceedings>


    <inproceedings key="torregrosa14p">
      <author>Juan Antonio Pérez-Ortiz, Daniel Torregrosa and Mikel Forcada</author>
      <title>Black-box integration of heterogeneous bilingual resources into an interactive translation system</title>
      <year>2014</year>
      <booktitle>EACL 2014 Workshop on Humans and Computer-assisted Translation</booktitle>
<!--      <pages></pages> -->
      <note>Gothenburg, April 26, 2014</note>
      <pdf-available/>
    </inproceedings>

<!--
Miquel Esplà-Gomis, Víctor M. Sánchez-Cartagena, Juan A. Pérez-Ortiz, Felipe
Sánchez-Martínez, Mikel L. Forcada and Rafael C. Carrasco: An efficient method to assist
non-expert users in extending dictionaries by assigning stems and inflectional paradigms
to unknown words 

-->
    <inproceedings key="esplagomis14p">
      <author>Esplà-Gomis, M., Sánchez-Cartagena, V.M., Pérez-Ortiz, J.A., Sánchez-Martínez, F., Forcada, M.L., Carrasco, R.C.</author>
      <title>An efficient method to assist non-expert users in
      extending dictionaries by assigning stems and inflectional
      paradigms to unknown words</title>
      <year>2014</year>
      <booktitle>Proceedings of EAMT 2014, The Seventeenth Annual Conference of the European Association for Machine Translation</booktitle>
     <pages>19-26</pages> 
      <note>Dubrovnik, June 16-18, 2014</note>
      <pdf-available/>
    </inproceedings>



    <inproceedings key="forcada14p">
      <author>Mikel L. Forcada</author>
      <title>On the Annotation of TMX Translation Memories for Advanced Leveraging in Computer-aided Translation</title>
      <year>2014</year>
      <booktitle>Proceedings of the Ninth International Conference on Language Resources and Evaluation (LREC'14)</booktitle>
      <pages>4374-4378</pages> 
      <note>Reykjavík, May 26-31, 2014. Revised version.</note>
      <pdf-available/>
      <pdfslides-available/>
    </inproceedings>

    <inproceedings key="espla-gomis12a">
      <author>Miquel Esplà-Gomis, Felipe Sánchez-Martínez, Mikel L. Forcada</author>
      <title>UAlacant: Using online machine translation for cross-lingual textual entailment</title>
      <year>2012</year>
      <booktitle>Proceedings of the 6th International Workshop on Semantic Evaluation (SemEval 2012)</booktitle>
      <pages>472-476</pages>
      <note>June 7-8, Montreal, Canada</note>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="tyers12a">
      <author>Francis M. Tyers, Felipe Sánchez-Martínez, Mikel L. Forcada</author>
      <title>Flexible finite-state lexical selection for rule-based machine translation</title>
      <year>2012</year>
      <booktitle>Proceedings of the 16th Annual Conference of the European Associtation for Machine Translation</booktitle>
      <pages>213-220</pages>
      <note>May 28-30, 2012, Trento, Italy</note>
	<pdf-available/>
    </inproceedings>

    <inproceedings key="espla-gomis11b">
      <author>Miquel Esplà-Gomis, Felipe Sánchez-Martínez, Mikel L Forcada</author>
      <title>Using machine translation in computer-aided translation to suggest the target-side words to change</title>
      <booktitle>Proceedings of the 13th Machine Translation Summit</booktitle>
      <pages>172-179</pages>
      <year>2011</year>
      <note>September 19-23, 2011, Xiamen, China</note>
    </inproceedings>

    <article key="sanchezmartinez11a">
      <author>Felipe Sánchez-Martínez, Mikel L. Forcada</author>
      <title>Free/open-source machine translation: Preface</title>
      <journal>Machine Translation</journal>
      <note>Special Issue on Free/Open-Source Machine Translation</note>
      <volume>25</volume>
      <number>2</number>
      <pages>83-86</pages>
      <year>2011</year>
    </article>

    <article key="forcada11apertium">
      <author>Mikel L. Forcada, Mireia Ginestí-Rosell, Jacob Nordfalk, Jim O'Regan, Sergio Ortiz-Rojas, Juan Antonio Pérez-Ortiz, Felipe Sánchez-Martínez, Gema Ramírez-Sánchez, Francis M. Tyers</author>
      <title>Apertium: a free/open-source platform for rule-based machine translation</title>
      <journal>Machine Translation</journal>
      <note>Special Issue on Free/Open-Source Machine Translation</note>
      <volume>25</volume>
      <number>2</number>
      <pages>127-144</pages>
      <year>2011</year>
    </article>
    
    <inproceedings key="dandapat11p">
		<author>Sandipan Dandapat, Sara Morrissey, Andy Way, Mikel L. Forcada</author>
		<title>Using Example-Based MT to Support Statistical MT when Translating
Homogeneous Data in a Resource-Poor Setting</title>
    <booktitle>Proceedings of the 15th Conference of the European Association for Machine Translation (EAMT 2011)</booktitle>
    <editors>Mikel L. Forcada, Heidi Depraetere, Vincent Vandeghinste</editors>
    <year>2011</year>
    <pages>201-208</pages>
    <pdf-available/>
    </inproceedings>
    

    <inproceedings key="dandapat10p">
      <author>Sandipan Dandapat, Mikel L. Forcada, Declan Groves,
      Sergio Penkale, John Tinsley, Andy Way</author> 
      <title>
      OpenMaTrEx: A Free/Open-Source Marker-Driven Example-Based
      Machine Translation System</title>
      <year>2010</year>
      <booktitle>Proceedings of IceTAL 2010</booktitle>
      <note>Reykjavík, 16-18 Aug. 2010</note>
	<pages>121-126</pages>
	<editors>Hrafn Loftsson, Eiríkur Rögnvaldsson, Sigrún Helgadóttir</editors	>
      <pdf-available/>
    </inproceedings>

    <inproceedings key="dcu-wmt2010">
      <author>Sergio Penkale, Rejwanul Haque, Sandipan Dandapat,
Pratyush Banerjee, Ankit K. Srivastava, Jinhua Du, Pavel Pecina, Sudip
Kumar Naskar, Mikel L. Forcada, Andy Way</author>
      <title>Matrex: the DCU MT system for WMT 2010</title>
      <booktitle>Proceedings of WMT 2010: The ACL 2010 Joint Fifth Workshop on Statistical Machine Translation and MetricsMATR</booktitle>
      <note>to be presented</note>
      <year>2010</year>
      <pdf-available/>
    </inproceedings>

    <article key="tyers10j">
      <author>Francis M. Tyers, Felipe Sánchez-Martínez, Sergio Ortiz Rojas, Mikel L. Forcada</author>
      <title>Free/open-source resources in the Apertium platform for machine translation research and development</title>
      <journal>The Prague Bulletin of Mathemathical Lingustics</journal>
      <year>2010</year>
      <volume>93</volume>
      <pages>67-76</pages>
      <note>Special Issue: Open Source Tools for Machine Translation (Fourth MT Marathon, Dublin 25-30.01.2010)</note>
      <pdf-available/>
    </article>

    <article key="esplagomis10j">
      <author>Miquel Esplà-Gomis, Mikel L. Forcada</author>
      <title>Combining Content-Based and URL-Based Heuristics to Harvest Aligned Bitexts from Multilingual Sites with Bitextor</title>
      <journal>The Prague Bulletin of Mathemathical Lingustics</journal>
      <year>2010</year>
      <volume>93</volume>
      <pages>77-86</pages>
      <note>Special Issue: Open Source Tools for Machine Translation (Fourth MT Marathon, Dublin 25-30.01.2010)</note>
      <pdf-available/>
    </article>

    <inproceedings key="forcada09p">
      <author> Mikel L. Forcada, Francis M. Tyers, Gema
      Ramírez-Sánchez</author>
      <title>The Apertium machine translation platform: five years on</title>
      <booktitle>Proceedings of
the First International Workshop on Free/Open-Source Rule-Based
Machine Translation</booktitle>
      <year>2009</year>
      <pages>3-10</pages>
      <note>Alacant, 02-03.11.2009</note>
      <editors>Juan Antonio Pérez-Ortiz, Felipe Sánchez-Martínez,
Francis M. Tyers</editors>
      <pdf-available/>
    </inproceedings>



    <inproceedings key="forcada09p2">
      <author>Felipe Sánchez-Martínez, Mikel L. Forcada, Andy Way</author>
      <title> Hybrid rule-based - example-based MT: feeding Apertium with sub-sentential translation units</title>
      <booktitle>Proceedings of the 3rd International Workshop on Example-Based Machine Translation</booktitle>
      <note>Dublin, 12-13.11.2009</note>
      <editors>Mikel L. Forcada, Andy Way</editors>
      <pages>11-18</pages>
      <year>2009</year>
      <pdf-available/>
      <pdfslides-available/>
    </inproceedings>

    <article key="forcada09j">
      <author>Mikel L. Forcada</author>
      <title>Apertium: traducció automàtica de codi obert per a les llengües romàniques</title>
      <journal>Linguamática</journal>
      <year>2009</year>
      <number>1</number>
      <pages>13-23</pages>
      <pdf-available/>
    </article>

    <article key="ginesti09j">
      <author>Mireia Ginestí Rosell, Mikel L. Forcada</author>
      <title>La traducció automàtica en la pràctica: aplicacions, dificultats i estratègies de desenvolupament</title>
      <journal>Caplletra</journal>
      <year>2009</year>
      <number>46</number>
      <pages>43-60</pages>
      <pdf-available/>
    </article>



    <article key="sanchez09j">
      <author>Felipe Sánchez-Martínez, Mikel L. Forcada</author>
      <title>Inferring Shallow-Transfer Machine Translation Rules from Small Parallel Corpora</title>
      <journal>Journal of Artificial Intelligence Research</journal>
      <year>2009</year>
      <volume>34</volume>
      <pages>605-635</pages>
      <pdf-available/>
    </article>

    <inproceedings key="espla09p">
      <author>Esplà-Gomis, M., Forcada, M.L.</author>
      <title>Bitextor, a free/open-source software to harvest translation memories from multilingual websites</title>
      <booktitle>Proceedings of the workshop {B}eyond {T}ranslation {M}emories: New Tools for Translators (at Machine Translation Summit XIII, Ottawa, Canada)</booktitle>
      <note>August 26-30, 2009</note>
      <year>2009</year>
      <pdf-available/>
    </inproceedings>

    
    <inproceedings key="caseli08p2">
      <title>On the automatic learning of bilingual resources: some relevant factors for machine translation</title>
      <author>Helena M. Caseli, Maria das Graças Volpe Nunes, Mikel L. Forcada</author>
      <booktitle>Lecture notes in Artificial Intelligence 5249: Proceedings
      of SBIA 2008</booktitle>
      <editors>G. Zaverucha and A. Loureiro da Costa</editors>
      <year>2008</year>
      <pages>258-267</pages>
      <pdf-available/>
    </inproceedings>


    <article key="armentanoooller08j">
      <author>C. Armentano-Oller, M.L. Forcada</author>
      <title>Reutilización de datos lingüísticos para la creación de un sistema de traducción automática para un nuevo par de lenguas</title>
      <journal>Procesamiento del Lenguaje Natural</journal>
      <number>41</number>
      <pages>243-250</pages>
      <year>2008</year>
      <pdf-available/>
    </article>


    <article key="forcada08j">
      <author>Mikel L. Forcada</author>
      <title>Katalanaren itzulpen automatikoa</title>
      <journal>Bat: Soziolinguistika Aldizkaria</journal>
      <note>Teknologi Berriak eta Euskara</note>
      <volume>66</volume>
      <number>1</number>
      <pages>167-171</pages>
      <year>2008</year>
     <pdf-available/>
    </article>


    <article key="caseli08j">
      <author>Helena M. Caseli, Maria das Graças V. Nunes, Mikel L. Forcada</author>